

/* 
    Solution by Rahul Surana
    
    ***********************************************************


You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



    ***********************************************************
*/


#include<bits/stdc++.h>

class Solution {
public:
    char findTheDifference(string s, string t) {
        int f[2][26] = { 0 };
        for(int i = 0 ; i < s.length(); i++){
            f[0][s[i]-'a']++;
        }
        for(int i = 0 ; i < t.length(); i++){
            f[1][t[i]-'a']++;
        }
        for(int i = 0; i < 26; i++) if(f[0][i] != f[1][i]) return i+'a';
        return '-';
    }
};