-- 53rd Solution
SELECT REPEAT('* ', @NUMBER := @NUMBER - 1)
FROM INFORMATION_SCHEMA.TABLES,
    (SELECT @NUMBER := 21) T
LIMIT 20

-- 54th Solution
SET @ROW := 0;
SELECT REPEAT('* ', @ROW := @ROW + 1)
FROM INFORMATION_SCHEMA.TABLES 
WHERE @ROW < 20

-- 55th Solution
SELECT GROUP_CONCAT(NUMB SEPARATOR '&')
FROM(
    SELECT @NUM := @NUM + 1 AS NUMB
    FROM INFORMATION_SCHEMA.TABLES T1,
        INFORMATION_SCHEMA.TABLES T2,
        (SELECT @NUM := 1) TMP
) TEMPNUM

WHERE NUMB <= 1000 AND NOT EXISTS(
    SELECT *
    FROM(
        SELECT @NUM1 := @NUM1 + 1 AS NUMA
            FROM INFORMATION_SCHEMA.TABLES T1,
                INFORMATION_SCHEMA.TABLES T2,
                (SELECT @NUM1 := 1) TMP1
                LIMIT 1000
        ) TEMPNUM1
     WHERE FLOOR(NUMB/NUMA) = (NUMB/NUMA) AND NUMA<NUMB AND NUMA>1
)