-- 41st Solution
SELECT ROUND(SQRT(POWER(MAX(LAT_N)  - MIN(LAT_N),  2) + POWER(MAX(LONG_W) - MIN(LONG_W), 2)), 4)
FROM STATION

-- 42nd Solution
SELECT ROUND(T.LAT, 4) AS MEDIAN
FROM (SELECT LAT_N AS LAT, ROW_NUMBER() OVER(ORDER BY LAT_N) AS ROWNUMBER FROM STATION) AS T
where T.ROWNUMBER=((SELECT COUNT(*) FROM STATION)+1)/2

-- 43rd Solution
SELECT SUM(CITY.POPULATION)
FROM CITY, COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT  = 'ASIA'

-- 44th Solution
SELECT CITY.NAME
FROM CITY, COUNTRY
WHERE CODE = COUNTRYCODE AND CONTINENT = 'AFRICA'

-- 45th Solution
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION))
FROM CITY INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
GROUP BY COUNTRY.CONTINENT
 