-- 24th Solution
SELECT CASE 
    WHEN P IS NULL
    THEN CONCAT(N, ' Root')
    
    WHEN N IN (SELECT DISTINCT P FROM BST) 
    THEN CONCAT(N, ' Inner')
    
    ELSE CONCAT(N, ' Leaf')
    END
FROM BST
ORDER BY N ASC 


-- 25th Solution
SELECT e.COMPANY_CODE, 
    (SELECT FOUNDER FROM company AS c WHERE c.COMPANY_CODE=e.COMPANY_CODE),
COUNT(DISTINCT e.LEAD_MANAGER_CODE),
COUNT(DISTINCT e.SENIOR_MANAGER_CODE),
COUNT(DISTINCT e.MANAGER_CODE),
COUNT(DISTINCT e.EMPLOYEE_CODE)
FROM EMPLOYEE AS e
GROUP BY e.COMPANY_CODE
ORDER BY e.COMPANY_CODE


-- 26TH Solution
SELECT COUNT(NAME)
FROM CITY
WHERE POPULATION > 100000

-- 27TH Solution
SELECT SUM(POPULATION)
FROM CITY
WHERE DISTRICT = 'California'

