-- 28th Solution
SELECT AVG(POPULATION)
FROM CITY
WHERE DISTRICT = 'California'

--29th Solution
SELECT FLOOR(AVG(POPULATION))
FROM CITY

-- 30th Solution
SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'JPN'

-- 31st Solution
SELECT MAX(POPULATION) - MIN(POPULATION)
FROM CITY

-- 32nd Solution
SELECT ROUND(AVG(SALARY)) - ROUND(AVG(REPLACE(SALARY, '0', '')))
FROM EMPLOYEES

-- 33rd Solution
SELECT SALARY * MONTHS AS EARNINGS, COUNT(*)
FROM EMPLOYEE
GROUP BY EARNINGS
ORDER BY EARNINGS DESC
LIMIT 1

-- 34th Solution
SELECT CONCAT(ROUND(SUM(LAT_N), 2), ' ',ROUND(SUM(LONG_W), 2) )
FROM STATION