-- 9th Solution
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION


-- 10th Solution
SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY), CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC
LIMIT 1;


-- 11th Solution
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[AEIOU].*'


-- 12th Solution
SELECT DISTINCT CITY
FROM STATION
WHERE RIGHT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u')


-- 13th Solution
SELECT DISTINCT CITY
FROM STATION 
WHERE LEFT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u')
        AND RIGHT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u')
        

-- 14th Solution
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou]'
