--  15th Solution 
SELECT DISTINCT CITY
FROM STATION
WHERE NOT RIGHT(CITY, 1) IN ('a', 'e', 'i', 'o', 'u')


--  16th Solution 
SELECT DISTINCT CITY 
FROM STATION 
WHERE CITY REGEXP '^[^aeiou]|[^aeiou]$'


--  17th Solution 
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou].*[^aeiou]$'


--  18th Solution 
SELECT NAME
FROM STUDENTS
WHERE MARKS > 75 
ORDER BY RIGHT(NAME, 3), ID


--  19th Solution 
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME 


--  20th Solution 
SELECT NAME
FROM EMPLOYEE
WHERE SALARY > 2000 AND MONTHS < 10
ORDER BY EMPLOYEE_ID
